run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused

issues:
  exclude-dirs:
    - internal/service/auth/mocks
    - internal/service/crud/mocks
