-- +goose Up
-- +goose StatementBegin

-- ==================== УПРАЖНЕНИЯ ДЛЯ НАЧИНАЮЩИХ (beginner) ====================

-- Upper Body для начинающих (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отжимания от стены', 'upper_body', 'Встаньте лицом к стене, руки на ширине плеч. Медленно сгибайте локти, приближаясь к стене', 12, 4, '/exercises/wall-pushup.gif', 'home', 0.56, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Подъемы рук с бутылками', 'upper_body', 'Возьмите бутылки с водой. Поднимайте руки через стороны вверх', 15, 4, '/exercises/lateral-raise.gif', 'home', 0.31, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Разгибание рук из-за головы', 'upper_body', 'Сядьте на стул, разгибайте руки с бутылкой вверх', 12, 4, '/exercises/overhead-extension.gif', 'home', 0.45, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Сгибание рук с бутылками', 'upper_body', 'Стоя, сгибайте руки в локтях с бутылками', 12, 4, '/exercises/bicep-curl.gif', 'home', 0.48, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Махи руками', 'upper_body', 'Стоя, выполняйте махи руками вперед-назад', 20, 4, '/exercises/arm-swings.gif', 'home', 0.14, 20);

-- Upper Body для начинающих (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Жим гантелей сидя', 'upper_body', 'Сидя на скамье, жим гантелей вверх', 12, 4, '/exercises/seated-dumbbell-press.gif', 'gym', 0.69, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Тяга верхнего блока', 'upper_body', 'На тренажере, тяга верхнего блока к груди', 12, 4, '/exercises/lat-pulldown.gif', 'gym', 0.66, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Разведение гантелей', 'upper_body', 'Стоя, разведение гантелей в стороны', 12, 4, '/exercises/dumbbell-fly.gif', 'gym', 0.59, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Тяга гантели в наклоне', 'upper_body', 'В наклоне, тяга гантели к поясу', 12, 4, '/exercises/dumbbell-row.gif', 'gym', 0.63, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Жим штанги лежа', 'upper_body', 'На скамье, жим штанги от груди', 10, 4, '/exercises/barbell-bench-press.gif', 'gym', 1.2, 60);

-- Upper Body для начинающих (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отжимания от скамьи', 'upper_body', 'Отжимания от скамьи обратным хватом на трицепс', 10, 4, '/exercises/bench-dips.gif', 'street', 0.85, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Подтягивания на низкой перекладине', 'upper_body', 'Низкая перекладина, подтягивания с опорой на ноги', 8, 4, '/exercises/australian-pullup.gif', 'street', 1.73, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отжимания от брусьев с поддержкой', 'upper_body', 'На брусьях с поддержкой ног', 6, 4, '/exercises/assisted-dips.gif', 'street', 2.5, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Вис на перекладине', 'upper_body', 'Простой вис для укрепления хвата', 1, 4, '/exercises/hanging.gif', 'street', 2.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отжимания от турника', 'upper_body', 'Стоя, отжимания от турника', 10, 4, '/exercises/bar-pushup.gif', 'street', 0.75, 45);

-- Lower Body для начинающих (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Приседания со стулом', 'lower_body', 'Приседания, касаясь стула', 15, 4, '/exercises/chair-squat.gif', 'home', 0.45, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады назад', 'lower_body', 'Поочередные выпады назад', 10, 4, '/exercises/reverse-lunge.gif', 'home', 0.9, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Подъемы на носки', 'lower_body', 'Подъемы на носки стоя', 20, 4, '/exercises/calf-raise.gif', 'home', 0.15, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Махи ногами вперед', 'lower_body', 'Стоя, махи ногами вперед', 12, 4, '/exercises/leg-swing.gif', 'home', 0.48, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Ягодичный мостик', 'lower_body', 'Лежа на спине, подъем таза', 15, 4, '/exercises/glute-bridge.gif', 'home', 0.35, 30);

-- Lower Body для начинающих (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Жим ногами в тренажере', 'lower_body', 'На тренажере, жим ногами', 15, 4, '/exercises/leg-press.gif', 'gym', 0.58, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Сгибание ног лежа', 'lower_body', 'На тренажере, сгибание ног', 15, 4, '/exercises/leg-curl.gif', 'gym', 0.4, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Разгибание ног сидя', 'lower_body', 'На тренажере, разгибание ног', 15, 4, '/exercises/leg-extension.gif', 'gym', 0.42, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Приседания с гантелями', 'lower_body', 'Приседания с гантелями в руках', 12, 4, '/exercises/goblet-squat.gif', 'gym', 0.98, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады с гантелями', 'lower_body', 'Выпады вперед с гантелями', 10, 4, '/exercises/dumbbell-lunge.gif', 'gym', 1.25, 60);

-- Lower Body для начинающих (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Приседания у стены', 'lower_body', 'Приседания спиной к стене', 15, 4, '/exercises/wall-sit.gif', 'street', 0.42, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады на месте', 'lower_body', 'Выпады на месте на каждую ногу', 12, 4, '/exercises/stationary-lunge.gif', 'street', 0.69, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Зашагивания на скамью', 'lower_body', 'Поочередные зашагивания на скамью', 10, 4, '/exercises/step-up.gif', 'street', 1.1, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Приседания с выпрыгиванием', 'lower_body', 'Приседания с легким выпрыгиванием', 10, 4, '/exercises/jump-squat.gif', 'street', 1.2, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады в сторону', 'lower_body', 'Выпады в сторону на каждую ногу', 10, 4, '/exercises/side-lunge.gif', 'street', 0.95, 40);

-- Full Body для начинающих (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Берпи без прыжка', 'full_body', 'Упрощенное берпи без прыжка', 8, 4, '/exercises/burpee-no-jump.gif', 'home', 1.25, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Медвежья походка', 'full_body', 'Передвижение на четвереньках', 10, 4, '/exercises/bear-crawl.gif', 'home', 0.85, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Ситапы', 'full_body', 'Полные подъемы корпуса', 15, 4, '/exercises/situp.gif', 'home', 0.43, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Планка с подъемом ноги', 'full_body', 'Планка с попеременным подъемом ног', 10, 4, '/exercises/plank-leg-lift.gif', 'home', 0.7, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады с поворотом', 'full_body', 'Выпад вперед с поворотом корпуса', 10, 4, '/exercises/lunge-twist.gif', 'home', 0.9, 30);

-- Full Body для начинающих (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Становая тяга', 'full_body', 'Классическая становая тяга с небольшим весом', 10, 4, '/exercises/deadlift.gif', 'gym', 1.8, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Приседания со штангой', 'full_body', 'Классические приседания со штангой', 10, 4, '/exercises/barbell-squat.gif', 'gym', 1.6, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Тяга верхнего блока к груди', 'full_body', 'Тяга верхнего блока с прямой спиной', 12, 4, '/exercises/lat-pulldown.gif', 'gym', 0.75, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Жим гантелей лежа', 'full_body', 'Жим гантелей на горизонтальной скамье', 10, 4, '/exercises/dumbbell-bench-press.gif', 'gym', 1.2, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Тяга гантели в наклоне', 'full_body', 'Тяга гантели к поясу в наклоне', 12, 4, '/exercises/dumbbell-row.gif', 'gym', 0.83, 45);

-- Full Body для начинающих (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Подтягивания на низкой перекладине', 'full_body', 'Подтягивания с опорой на ноги', 8, 4, '/exercises/australian-pullup.gif', 'street', 1.63, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отжимания от скамьи с подъемом ноги', 'full_body', 'Отжимания с попеременным подъемом ноги', 8, 4, '/exercises/bench-pushup-leg-lift.gif', 'street', 1.25, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Берпи на скамье', 'full_body', 'Берпи с опорой на скамью', 8, 4, '/exercises/bench-burpee.gif', 'street', 1.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Зашагивания на скамью с махом', 'full_body', 'Зашагивание с махом рук', 10, 4, '/exercises/step-up-arm-swing.gif', 'street', 1.1, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Выпады с опорой на скамью', 'full_body', 'Выпады назад с опорой на скамью', 10, 4, '/exercises/bench-lunge.gif', 'street', 1.05, 30);

-- Cardio для начинающих (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Бег на месте', 'cardio', 'Бег на месте с высоким подниманием колен', 30, 4, '/exercises/high-knees.gif', 'home', 8.5, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Прыжки с разведением рук и ног', 'cardio', 'Классические прыжки ноги вместе-врозь', 20, 4, '/exercises/jumping-jacks.gif', 'home', 7.0, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Скалолаз в медленном темпе', 'cardio', 'Поочередное подтягивание коленей в упоре лежа', 20, 4, '/exercises/mountain-climber.gif', 'home', 9.5, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Боксирование с тенью', 'cardio', 'Удары руками в воздух', 30, 4, '/exercises/shadow-boxing.gif', 'home', 6.5, 15),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Отведение ног назад в прыжке', 'cardio', 'Прыжки с захлестом голени', 25, 4, '/exercises/butt-kicks.gif', 'home', 7.5, 15);

-- Cardio для начинающих (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Ходьба на беговой дорожке', 'cardio', 'Быстрая ходьба с небольшим наклоном', 1, 4, '/exercises/treadmill-walk.gif', 'gym', 5.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Велотренажер', 'cardio', 'Езда на велотренажере в умеренном темпе', 1, 4, '/exercises/stationary-bike.gif', 'gym', 7.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Эллиптический тренажер', 'cardio', 'Ходьба на эллипсоиде', 1, 4, '/exercises/elliptical.gif', 'gym', 8.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Гребной тренажер', 'cardio', 'Гребля на тренажере', 1, 4, '/exercises/rowing-machine.gif', 'gym', 9.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Степпер', 'cardio', 'Ходьба на степпере', 1, 4, '/exercises/stepper.gif', 'gym', 6.5, 30);

-- Cardio для начинающих (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Бег трусцой', 'cardio', 'Легкий бег в умеренном темпе', 1, 4, '/exercises/jogging.gif', 'street', 10.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Скандинавская ходьба', 'cardio', 'Ходьба с палками', 1, 4, '/exercises/nordic-walking.gif', 'street', 6.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Прыжки через скакалку', 'cardio', 'Прыжки на скакалке в умеренном темпе', 50, 4, '/exercises/jump-rope.gif', 'street', 11.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Подъем по лестнице', 'cardio', 'Ходьба по лестнице', 1, 4, '/exercises/stairs.gif', 'street', 9.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Бег с высоким подниманием бедра', 'cardio', 'Бег на месте с высоким подъемом коленей', 30, 4, '/exercises/high-knees-street.gif', 'street', 9.5, 20);

-- Flexibility для начинающих (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Наклоны к ногам сидя', 'flexibility', 'Сидя на полу, наклоны к прямым ногам', 10, 4, '/exercises/seated-forward-bend.gif', 'home', 3.5, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка квадрицепса стоя', 'flexibility', 'Стоя, растяжка передней поверхности бедра', 10, 4, '/exercises/standing-quad-stretch.gif', 'home', 3.0, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка грудных мышц', 'flexibility', 'Растяжка груди у стены', 8, 4, '/exercises/chest-stretch.gif', 'home', 2.8, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Поза ребенка', 'flexibility', 'Растяжка спины в позе ребенка', 5, 4, '/exercises/child-pose.gif', 'home', 2.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка трицепса', 'flexibility', 'Растяжка трицепса за головой', 8, 4, '/exercises/triceps-stretch.gif', 'home', 2.5, 15);

-- Flexibility для начинающих (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка на коврике', 'flexibility', 'Комплекс растяжки на матах', 8, 4, '/exercises/mat-stretch.gif', 'gym', 4.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка с фитболом', 'flexibility', 'Растяжка спины на фитболе', 6, 4, '/exercises/ball-stretch.gif', 'gym', 4.2, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Вис на перекладине', 'flexibility', 'Растяжка позвоночника в висе', 3, 4, '/exercises/hanging-stretch.gif', 'gym', 3.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка с эспандером', 'flexibility', 'Растяжка рук с эспандером', 10, 4, '/exercises/band-stretch.gif', 'gym', 3.2, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'beginner', 'Растяжка на скамье', 'flexibility', 'Растяжка спины на скамье', 6, 4, '/exercises/bench-stretch.gif', 'gym', 3.3, 20);

-- Flexibility для начинающих (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
    (gen_random_uuid(), 'beginner', 'Растяжка на турнике', 'flexibility', 'Вис с расслаблением', 3, 4, '/exercises/bar-hang.gif', 'street', 3.2, 30);

-- ==================== УПРАЖНЕНИЯ ДЛЯ СРЕДНЕГО УРОВНЯ (medium) ====================

-- Upper Body для среднего уровня (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Классические отжимания', 'upper_body', 'Упор лежа, руки на ширине плеч. Опускайтесь до касания грудью пола', 12, 4, '/exercises/pushup.gif', 'home', 1.04, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания алмазные', 'upper_body', 'Узкая постановка рук для трицепса', 10, 4, '/exercises/diamond-pushup.gif', 'home', 1.4, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания с ногами на возвышении', 'upper_body', 'Ноги на стуле, руки на полу', 10, 4, '/exercises/decline-pushup.gif', 'home', 1.55, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания широким хватом', 'upper_body', 'Широкая постановка рук для груди', 12, 4, '/exercises/wide-pushup.gif', 'home', 1.08, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания с поднятой ногой', 'upper_body', 'Отжимания с ногой на возвышении', 10, 4, '/exercises/pike-pushup.gif', 'home', 1.45, 45);

-- Upper Body для среднего уровня (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Жим штанги стоя', 'upper_body', 'Стоя, жим штанги с груди вверх', 8, 4, '/exercises/standing-military-press.gif', 'gym', 2.25, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Тяга штанги в наклоне', 'upper_body', 'В наклоне, тяга штанги к поясу', 8, 4, '/exercises/bent-over-row.gif', 'gym', 2.06, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Жим гантелей на наклонной скамье', 'upper_body', 'На наклонной скамье, жим гантелей', 10, 4, '/exercises/incline-dumbbell-press.gif', 'gym', 1.5, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Пуловер с гантелью', 'upper_body', 'Лежа на скамье, пуловер с гантелью', 12, 4, '/exercises/dumbbell-pullover.gif', 'gym', 1.04, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Шраги с гантелями', 'upper_body', 'Подъем плеч с гантелями', 15, 4, '/exercises/dumbbell-shrug.gif', 'gym', 0.63, 45);

-- Upper Body для среднего уровня (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Подтягивания средним хватом', 'upper_body', 'Классические подтягивания', 8, 4, '/exercises/pullup.gif', 'street', 2.5, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Подтягивания обратным хватом', 'upper_body', 'Хват снизу для бицепса', 8, 4, '/exercises/chinup.gif', 'street', 2.38, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания на брусьях', 'upper_body', 'Классические отжимания на брусьях', 10, 4, '/exercises/dips.gif', 'street', 1.85, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Подтягивания широким хватом', 'upper_body', 'Широкий хват для спины', 8, 4, '/exercises/wide-pullup.gif', 'street', 2.63, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Австралийские подтягивания', 'upper_body', 'Низкая перекладина, подтягивания', 12, 4, '/exercises/australian-pullup-advanced.gif', 'street', 1.17, 60);

-- Lower Body для среднего уровня (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Приседания с выпрыгиванием', 'lower_body', 'Глубокие приседания с прыжком вверх', 15, 4, '/exercises/jump-squat-advanced.gif', 'home', 1.07, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады с прыжком', 'lower_body', 'Смена ног в прыжке', 12, 4, '/exercises/jumping-lunge.gif', 'home', 1.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Болгарские сплит-приседания', 'lower_body', 'Задняя нога на стуле', 10, 4, '/exercises/bulgarian-split-squat.gif', 'home', 1.9, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Приседания с паузой', 'lower_body', 'Приседания с паузой в нижней точке', 12, 4, '/exercises/pause-squat.gif', 'home', 1.21, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Зашагивания на стул с весом', 'lower_body', 'Зашагивания на стул с гантелями', 12, 4, '/exercises/step-up-weighted.gif', 'home', 1.38, 45);

-- Lower Body для среднего уровня (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Приседания со штангой', 'lower_body', 'Классические приседания со штангой', 10, 4, '/exercises/barbell-squat.gif', 'gym', 2.4, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Румынская тяга', 'lower_body', 'Тяга с прямыми ногами', 10, 4, '/exercises/romanian-deadlift.gif', 'gym', 2.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады со штангой', 'lower_body', 'Выпады вперед со штангой', 8, 4, '/exercises/barbell-lunge.gif', 'gym', 2.75, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Гакк-приседания', 'lower_body', 'В тренажере Гаккеншмидта', 12, 4, '/exercises/hack-squat.gif', 'gym', 1.5, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Сгибание ног лежа с весом', 'lower_body', 'На тренажере, сгибание ног', 15, 4, '/exercises/leg-curl-weighted.gif', 'gym', 0.8, 60);

-- Lower Body для среднего уровня (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Приседания на одной ноге', 'lower_body', 'Пистолетик у опоры', 8, 4, '/exercises/pistol-squat.gif', 'street', 2.88, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады с запрыгиванием на скамью', 'lower_body', 'Выпад и запрыгивание на скамью', 10, 4, '/exercises/lunge-to-box.gif', 'street', 2.1, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Спринтерские выпады', 'lower_body', 'Быстрая смена ног в выпаде', 16, 4, '/exercises/split-squat-jump.gif', 'street', 1.06, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Зашагивания с прыжком на тумбу', 'lower_body', 'Зашагивание с прыжком', 10, 4, '/exercises/box-jump.gif', 'street', 2.2, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады в сторону с прыжком', 'lower_body', 'Боковые выпады с прыжком', 12, 4, '/exercises/side-lunge-jump.gif', 'street', 1.54, 45);

-- Full Body для среднего уровня (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Берпи с отжиманием', 'full_body', 'Полное берпи с отжиманием и прыжком', 12, 4, '/exercises/burpee.gif', 'home', 1.25, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Медвежья походка с отжиманием', 'full_body', 'Передвижение с отжиманием', 10, 4, '/exercises/bear-crawl-pushup.gif', 'home', 1.4, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Ситапы с весом', 'full_body', 'Ситапы с блином за головой', 15, 4, '/exercises/weighted-situp.gif', 'home', 0.8, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Планка с переходом', 'full_body', 'Переход с рук на локти и обратно', 16, 4, '/exercises/plank-walkout.gif', 'home', 0.66, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады с поворотом и весом', 'full_body', 'Выпады с поворотом корпуса с блином', 12, 4, '/exercises/lunge-twist-weight.gif', 'home', 1.17, 45);

-- Full Body для среднего уровня (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Становая тяга', 'full_body', 'Классическая становая тяга', 8, 4, '/exercises/deadlift.gif', 'gym', 3.5, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Приседания со штангой на груди', 'full_body', 'Фронтальные приседания', 8, 4, '/exercises/front-squat.gif', 'gym', 3.25, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Тяга верхнего блока к груди', 'full_body', 'Тяга с акцентом на спину', 12, 4, '/exercises/lat-pulldown-advanced.gif', 'gym', 1.17, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Жим гантелей стоя', 'full_body', 'Жим гантелей стоя с вовлечением ног', 10, 4, '/exercises/standing-dumbbell-press.gif', 'gym', 1.6, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Тяга штанги к подбородку', 'full_body', 'Штанга к подбородку', 12, 4, '/exercises/upright-row.gif', 'gym', 1.25, 60);

-- Full Body для среднего уровня (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Подтягивания с выходом', 'full_body', 'Подтягивания с частичным выходом', 6, 4, '/exercises/pullup-partial.gif', 'street', 4.0, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Берпи с подтягиванием', 'full_body', 'Берпи и подтягивание на турнике', 8, 4, '/exercises/burpee-pullup.gif', 'street', 3.25, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Отжимания на брусьях с подъемом ног', 'full_body', 'Отжимания с подъемом ног', 10, 4, '/exercises/dips-leg-raise.gif', 'street', 2.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Зашагивания с жимом над головой', 'full_body', 'Зашагивание с воображаемым жимом', 12, 4, '/exercises/step-up-press.gif', 'street', 1.42, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады с подтягиванием', 'full_body', 'Выпад и имитация подтягивания', 12, 4, '/exercises/lunge-pullup-mime.gif', 'street', 1.33, 45);

-- Cardio для среднего уровня (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Берпи с прыжком', 'cardio', 'Берпи с высоким прыжком', 15, 4, '/exercises/burpee-jump.gif', 'home', 12.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Скалолаз в быстром темпе', 'cardio', 'Быстрая смена ног в упоре лежа', 40, 4, '/exercises/mountain-climber-fast.gif', 'home', 11.5, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Джампинг Джекс', 'cardio', 'Прыжки ноги вместе-врозь', 40, 4, '/exercises/jumping-jacks-fast.gif', 'home', 9.5, 15),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Бёрпи с отжиманием', 'cardio', 'Классическое берпи', 12, 4, '/exercises/burpee.gif', 'home', 13.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Бег с захлестом голени', 'cardio', 'Бег на месте с захлестом', 50, 4, '/exercises/butt-kicks-fast.gif', 'home', 10.0, 15);

-- Cardio для среднего уровня (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Интервальный бег на дорожке', 'cardio', 'Чередование быстрого и медленного бега', 1, 4, '/exercises/treadmill-interval.gif', 'gym', 12.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Сайклинг', 'cardio', 'Интенсивная езда на велотренажере', 1, 4, '/exercises/cycling-intensive.gif', 'gym', 13.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Гребля', 'cardio', 'Гребля в интенсивном темпе', 1, 4, '/exercises/rowing-intensive.gif', 'gym', 14.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Берпи на месте', 'cardio', 'Берпи в зале', 20, 4, '/exercises/burpee-gym.gif', 'gym', 15.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Скакалка', 'cardio', 'Прыжки на скакалке в быстром темпе', 100, 4, '/exercises/jump-rope-fast.gif', 'gym', 14.5, 20);

-- Cardio для среднего уровня (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Интервальный бег', 'cardio', 'Чередование спринта и трусцы', 1, 4, '/exercises/interval-running.gif', 'street', 14.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Бег по лестнице', 'cardio', 'Бег вверх по лестнице', 1, 4, '/exercises/stairs-running.gif', 'street', 16.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Скакалка на улице', 'cardio', 'Прыжки на скакалке в быстром темпе', 150, 4, '/exercises/jump-rope-outdoor.gif', 'street', 15.0, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Фартлек', 'cardio', 'Бег с переменной скоростью', 1, 4, '/exercises/fartlek.gif', 'street', 14.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Бёрпи на улице', 'cardio', 'Берпи на открытом воздухе', 20, 4, '/exercises/burpee-street.gif', 'street', 15.5, 30);

-- Flexibility для среднего уровня (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Продольный шпагат', 'flexibility', 'Растяжка на продольный шпагат', 6, 4, '/exercises/front-split.gif', 'home', 4.0, 40),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Поперечный шпагат', 'flexibility', 'Растяжка на поперечный шпагат', 6, 4, '/exercises/side-split.gif', 'home', 4.5, 40),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Мостик', 'flexibility', 'Гимнастический мостик', 6, 4, '/exercises/bridge.gif', 'home', 5.0, 40),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Бабочка с наклоном', 'flexibility', 'Сидя, стопы вместе, наклон вперед', 10, 4, '/exercises/butterfly-stretch.gif', 'home', 3.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Складка сидя', 'flexibility', 'Глубокая складка сидя', 8, 4, '/exercises/seated-fold.gif', 'home', 3.8, 30);

-- Flexibility для среднего уровня (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка на шведской стенке', 'flexibility', 'Растяжка ног у шведской стенки', 8, 4, '/exercises/wall-stretch.gif', 'gym', 4.5, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка с фитболом', 'flexibility', 'Растяжка спины на фитболе', 6, 4, '/exercises/ball-stretch-advanced.gif', 'gym', 5.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Вис с отягощением', 'flexibility', 'Растяжка позвоночника в висе с грузом', 3, 4, '/exercises/hanging-weight.gif', 'gym', 5.5, 40),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка с эспандером', 'flexibility', 'Глубокая растяжка с эспандером', 10, 4, '/exercises/band-stretch-advanced.gif', 'gym', 4.2, 25),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Поза голубя', 'flexibility', 'Растяжка ягодиц', 8, 4, '/exercises/pigeon-pose.gif', 'gym', 4.0, 30);

-- Flexibility для среднего уровня (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка на турнике', 'flexibility', 'Вис с растяжкой', 4, 4, '/exercises/bar-hang-stretch.gif', 'street', 4.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка у опоры', 'flexibility', 'Глубокая растяжка ног', 8, 4, '/exercises/leg-stretch-deep.gif', 'street', 4.5, 25),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Наклоны к ногам стоя', 'flexibility', 'Глубокие наклоны', 12, 4, '/exercises/standing-forward-bend-deep.gif', 'street', 4.2, 20),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Растяжка на брусьях', 'flexibility', 'Растяжка на брусьях', 6, 4, '/exercises/bars-stretch.gif', 'street', 4.8, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'medium', 'Выпады с глубокой растяжкой', 'flexibility', 'Глубокие выпады с растяжкой', 8, 4, '/exercises/lunge-deep-stretch.gif', 'street', 5.0, 30);

-- ==================== УПРАЖНЕНИЯ ДЛЯ ПРОДВИНУТЫХ (sportsman) ====================

-- Upper Body для продвинутых (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Отжимания с хлопком', 'upper_body', 'Взрывные отжимания с хлопком', 15, 4, '/exercises/clap-pushup.gif', 'home', 1.67, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Отжимания в стойке на руках у стены', 'upper_body', 'Вертикальные отжимания', 8, 4, '/exercises/handstand-pushup.gif', 'home', 4.38, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Индийские отжимания', 'upper_body', 'Дзюдо-отжимания', 15, 4, '/exercises/hindu-pushup.gif', 'home', 1.47, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Отжимания с поднятыми ногами', 'upper_body', 'Отжимания с ногами на возвышении', 15, 4, '/exercises/decline-pushup-advanced.gif', 'home', 1.73, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Планка с отжиманием', 'upper_body', 'Переходы в планке с отжиманием', 12, 4, '/exercises/plank-pushup.gif', 'home', 2.0, 60);

-- Upper Body для продвинутых (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Жим штанги лежа с весом', 'upper_body', 'Жим лежа с большим весом', 6, 4, '/exercises/heavy-bench-press.gif', 'gym', 5.33, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Тяга штанги в наклоне с весом', 'upper_body', 'Тяга с большим весом', 6, 4, '/exercises/heavy-bent-over-row.gif', 'gym', 5.0, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Жим Арнольда', 'upper_body', 'Жим с поворотом кистей', 10, 4, '/exercises/arnold-press.gif', 'gym', 2.6, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Тяга Т-штанги', 'upper_body', 'Тяга в наклоне в тренажере', 8, 4, '/exercises/t-bar-row.gif', 'gym', 3.5, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Жим Свенда', 'upper_body', 'Жим с блином перед собой', 12, 4, '/exercises/svend-press.gif', 'gym', 1.67, 60);

-- Upper Body для продвинутых (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Подтягивания с весом', 'upper_body', 'Подтягивания с дополнительным весом', 8, 4, '/exercises/weighted-pullup.gif', 'street', 4.38, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Выход силой', 'upper_body', 'Выход силой на турнике', 5, 4, '/exercises/muscle-up.gif', 'street', 9.0, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Отжимания на брусьях с весом', 'upper_body', 'Отжимания с дополнительным весом', 8, 4, '/exercises/weighted-dips.gif', 'street', 4.75, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Подтягивания широким хватом с весом', 'upper_body', 'Широкие подтягивания с весом', 6, 4, '/exercises/weighted-wide-pullup.gif', 'street', 6.67, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Подтягивания с хлопком', 'upper_body', 'Взрывные подтягивания с хлопком', 6, 4, '/exercises/clap-pullup.gif', 'street', 7.0, 120);

-- Lower Body для продвинутых (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания пистолетиком', 'lower_body', 'Приседания на одной ноге без опоры', 8, 4, '/exercises/pistol-squat-advanced.gif', 'home', 4.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Выпады с запрыгиванием на тумбу', 'lower_body', 'Выпад и прыжок на возвышение', 10, 4, '/exercises/lunge-to-box-advanced.gif', 'home', 3.4, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания с выпрыгиванием на тумбу', 'lower_body', 'Прыжки на тумбу из приседа', 8, 4, '/exercises/box-squat-jump.gif', 'home', 4.5, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с отжиманием и прыжком на тумбу', 'lower_body', 'Сложное берпи с прыжком', 8, 4, '/exercises/burpee-box-jump.gif', 'home', 4.75, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Зашагивания с прыжком и коленом', 'lower_body', 'Сложные зашагивания', 10, 4, '/exercises/step-up-knee-advanced.gif', 'home', 3.2, 60);

-- Lower Body для продвинутых (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания со штангой с весом', 'lower_body', 'Тяжелые приседания', 5, 4, '/exercises/heavy-squat.gif', 'gym', 8.0, 180),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Становая тяга с весом', 'lower_body', 'Тяжелая становая тяга', 5, 4, '/exercises/heavy-deadlift.gif', 'gym', 9.0, 180),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания над головой', 'lower_body', 'Оверхед-приседания', 6, 4, '/exercises/overhead-squat.gif', 'gym', 6.33, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания в ножницы со штангой', 'lower_body', 'Разножка со штангой', 8, 4, '/exercises/barbell-split-squat-advanced.gif', 'gym', 4.38, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Тяга сумо', 'lower_body', 'Становая тяга сумо', 6, 4, '/exercises/sumo-deadlift.gif', 'gym', 7.0, 150);

-- Lower Body для продвинутых (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания с прыжком на высокую тумбу', 'lower_body', 'Прыжки на высокую тумбу', 6, 4, '/exercises/box-jump-high.gif', 'street', 7.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Выпады с прыжком в высоту', 'lower_body', 'Взрывные выпады', 10, 4, '/exercises/jump-lunge-advanced.gif', 'street', 3.8, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Приседания на одной ноге с прыжком', 'lower_body', 'Пистолетик с прыжком', 6, 4, '/exercises/single-leg-jump-squat-advanced.gif', 'street', 6.67, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с запрыгиванием на тумбу', 'lower_body', 'Берпи с прыжком', 8, 4, '/exercises/burpee-box-jump-advanced.gif', 'street', 5.5, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Зашагивания с прыжком и сменой ноги', 'lower_body', 'Сложные зашагивания', 10, 4, '/exercises/step-up-switch-advanced.gif', 'street', 3.6, 60);

-- Full Body для продвинутых (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с отжиманием и прыжком на тумбу', 'full_body', 'Сложное берпи', 8, 4, '/exercises/burpee-box-jump-advanced.gif', 'home', 5.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с подтягиванием', 'full_body', 'Берпи и подтягивание', 6, 4, '/exercises/burpee-pullup-advanced.gif', 'home', 7.5, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Отжимания в стойке на руках', 'full_body', 'Отжимания без опоры', 5, 4, '/exercises/handstand-pushup-free.gif', 'home', 9.6, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с отжиманием и хлопком', 'full_body', 'Взрывное берпи', 10, 4, '/exercises/burpee-clap.gif', 'home', 3.8, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Комплексное упражнение', 'full_body', 'Сочетание приседа, отжимания и прыжка', 12, 4, '/exercises/complex.gif', 'home', 3.5, 60);

-- Full Body для продвинутых (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Кроссфит комплекс', 'full_body', 'Сочетание нескольких упражнений', 5, 4, '/exercises/crossfit-complex.gif', 'gym', 10.0, 180),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Взятие штанги на грудь', 'full_body', 'Олимпийское движение', 5, 4, '/exercises/clean.gif', 'gym', 9.6, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Толчок штанги', 'full_body', 'Толчок от груди', 5, 4, '/exercises/jerk.gif', 'gym', 9.8, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Рывок штанги', 'full_body', 'Олимпийский рывок', 4, 4, '/exercises/snatch.gif', 'gym', 13.0, 180),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Тяжелоатлетический комплекс', 'full_body', 'Комбинация движений', 4, 4, '/exercises/weightlifting-complex.gif', 'gym', 13.75, 180);

-- Full Body для продвинутых (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Воркаут комплекс', 'full_body', 'Подтягивания, отжимания, приседания', 3, 4, '/exercises/workout-complex.gif', 'street', 14.67, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Выход силой с отжиманиями', 'full_body', 'Выход и отжимания', 5, 4, '/exercises/muscle-up-dips.gif', 'street', 9.6, 150),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Подтягивания с отжиманиями на брусьях', 'full_body', 'Комбинация', 6, 4, '/exercises/pullup-dips-combo.gif', 'street', 7.67, 120),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с подтягиванием', 'full_body', 'Берпи + подтягивание', 8, 4, '/exercises/burpee-pullup-advanced.gif', 'street', 5.88, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Силовой комплекс на турнике', 'full_body', 'Серия упражнений на турнике', 4, 4, '/exercises/bar-complex.gif', 'street', 12.25, 150);

-- Cardio для продвинутых (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с двойным отжиманием', 'cardio', 'Берпи с двумя отжиманиями', 15, 4, '/exercises/double-burpee.gif', 'home', 18.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Скалолаз взрывной', 'cardio', 'Максимально быстрая смена ног', 60, 4, '/exercises/mountain-climber-explosive.gif', 'home', 16.0, 15),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Джампинг Джекс взрывные', 'cardio', 'Прыжки с максимальной амплитудой', 50, 4, '/exercises/jumping-jacks-explosive.gif', 'home', 14.0, 15),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи с прыжком в высоту', 'cardio', 'Берпи с максимальным прыжком', 15, 4, '/exercises/burpee-high-jump.gif', 'home', 19.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Интервальный комплекс', 'cardio', 'Чередование упражнений', 1, 4, '/exercises/interval-complex.gif', 'home', 20.0, 15);

-- Cardio для продвинутых (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Спринт на дорожке', 'cardio', 'Максимальный спринт', 1, 4, '/exercises/treadmill-sprint.gif', 'gym', 18.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Сайклинг спринт', 'cardio', 'Взрывная езда', 1, 4, '/exercises/bike-sprint.gif', 'gym', 17.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Гребля спринт', 'cardio', 'Взрывная гребля', 1, 4, '/exercises/rowing-sprint.gif', 'gym', 19.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Эргометр', 'cardio', 'Работа на гребном тренажере', 1, 4, '/exercises/ergometer.gif', 'gym', 16.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Табата на велосипеде', 'cardio', 'Интервальная тренировка', 1, 4, '/exercises/tabata-bike.gif', 'gym', 20.0, 45);

-- Cardio для продвинутых (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Спринт в горку', 'cardio', 'Бег в гору максимально', 1, 4, '/exercises/hill-sprint.gif', 'street', 21.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Лестничный спринт', 'cardio', 'Бег по лестнице максимально', 1, 4, '/exercises/stairs-sprint.gif', 'street', 22.0, 90),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Скакалка двойные', 'cardio', 'Прыжки с двойным прокрутом', 50, 4, '/exercises/double-unders.gif', 'street', 18.0, 30),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Фартлек сложный', 'cardio', 'Переменный бег', 1, 4, '/exercises/fartlek-advanced.gif', 'street', 20.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Берпи спринт', 'cardio', 'Берпи в максимальном темпе', 20, 4, '/exercises/burpee-sprint.gif', 'street', 21.0, 30);

-- Flexibility для продвинутых (home)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Шпагат продольный', 'flexibility', 'Полный продольный шпагат', 8, 4, '/exercises/front-split-full.gif', 'home', 5.5, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Шпагат поперечный', 'flexibility', 'Полный поперечный шпагат', 8, 4, '/exercises/side-split-full.gif', 'home', 6.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Мостик с подъемом', 'flexibility', 'Мостик и подъем', 8, 4, '/exercises/bridge-leg-lift.gif', 'home', 6.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Складка с захватом', 'flexibility', 'Глубокая складка', 10, 4, '/exercises/seated-fold-hold.gif', 'home', 5.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Колечко', 'flexibility', 'Растяжка спины', 6, 4, '/exercises/ring-stretch.gif', 'home', 6.0, 45);

-- Flexibility для продвинутых (gym)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Растяжка на шведской стенке', 'flexibility', 'Глубокая растяжка', 8, 4, '/exercises/wall-stretch-advanced.gif', 'gym', 6.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Растяжка с партнером', 'flexibility', 'Пассивная растяжка', 6, 4, '/exercises/partner-stretch.gif', 'gym', 6.5, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Вис с отягощением', 'flexibility', 'Вис с дополнительным весом', 5, 4, '/exercises/hanging-heavy.gif', 'gym', 7.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Растяжка на пьедестале', 'flexibility', 'Растяжка с возвышения', 8, 4, '/exercises/platform-stretch.gif', 'gym', 5.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Комплексная растяжка', 'flexibility', 'Полный комплекс', 1, 4, '/exercises/comprehensive-stretch.gif', 'gym', 8.0, 90);

-- Flexibility для продвинутых (street)
INSERT INTO bodyfuel.exercise (id, level_preparation, name, type_exercise, description, base_count_reps, steps, link_gif, place_exercise, avg_calories_per, base_relax_time) VALUES
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Шпагат на возвышении', 'flexibility', 'Шпагат с передней ногой на возвышении', 8, 4, '/exercises/split-elevated.gif', 'street', 7.0, 60),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Вис с растяжкой', 'flexibility', 'Вис и растяжка', 6, 4, '/exercises/hanging-stretch-advanced.gif', 'street', 5.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Растяжка на брусьях', 'flexibility', 'Растяжка в висе на брусьях', 8, 4, '/exercises/bars-stretch-advanced.gif', 'street', 6.5, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Мостик на улице', 'flexibility', 'Мостик на траве', 8, 4, '/exercises/bridge-outdoor.gif', 'street', 6.0, 45),
                                                                                                                                                                                 (gen_random_uuid(), 'sportsman', 'Комплекс на растяжку', 'flexibility', 'Полный комплекс на улице', 1, 4, '/exercises/outdoor-stretch-complex.gif', 'street', 8.5, 90);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
TRUNCATE bodyfuel.exercise;
-- +goose StatementEnd