// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "backend/internal/dto"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// ExercisesRepository is an autogenerated mock type for the ExercisesRepository type
type ExercisesRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, exercise
func (_m *ExercisesRepository) Create(ctx context.Context, exercise *entities.Exercise) error {
	ret := _m.Called(ctx, exercise)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Exercise) error); ok {
		r0 = rf(ctx, exercise)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Get provides a mock function with given fields: ctx, f, withBlock
func (_m *ExercisesRepository) Get(ctx context.Context, f dto.ExerciseFilter, withBlock bool) (*entities.Exercise, error) {
	ret := _m.Called(ctx, f, withBlock)
	if len(ret) == 0 {
		panic("no return value specified for Get")
	}
	var r0 *entities.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExerciseFilter, bool) (*entities.Exercise, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExerciseFilter, bool) *entities.Exercise); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Exercise)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, dto.ExerciseFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Update provides a mock function with given fields: ctx, exercise
func (_m *ExercisesRepository) Update(ctx context.Context, exercise *entities.Exercise) error {
	ret := _m.Called(ctx, exercise)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Exercise) error); ok {
		r0 = rf(ctx, exercise)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Delete provides a mock function with given fields: ctx, f
func (_m *ExercisesRepository) Delete(ctx context.Context, f dto.ExerciseFilter) error {
	ret := _m.Called(ctx, f)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExerciseFilter) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// List provides a mock function with given fields: ctx, f, withBlock
func (_m *ExercisesRepository) List(ctx context.Context, f dto.ExerciseFilter, withBlock bool) ([]*entities.Exercise, error) {
	ret := _m.Called(ctx, f, withBlock)
	if len(ret) == 0 {
		panic("no return value specified for List")
	}
	var r0 []*entities.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExerciseFilter, bool) ([]*entities.Exercise, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ExerciseFilter, bool) []*entities.Exercise); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Exercise)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, dto.ExerciseFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewExercisesRepository creates a new instance of ExercisesRepository.
func NewExercisesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExercisesRepository {
	mock := &ExercisesRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
