// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "backend/internal/dto"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserParamsRepository is an autogenerated mock type for the UserParamsRepository type
type UserParamsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userParams
func (_m *UserParamsRepository) Create(ctx context.Context, userParams *entities.UserParams) error {
	ret := _m.Called(ctx, userParams)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserParams) error); ok {
		r0 = rf(ctx, userParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, f
func (_m *UserParamsRepository) Delete(ctx context.Context, f dto.UserParamsFilter) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserParamsFilter) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, f, withBlock
func (_m *UserParamsRepository) Get(ctx context.Context, f dto.UserParamsFilter, withBlock bool) (*entities.UserParams, error) {
	ret := _m.Called(ctx, f, withBlock)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.UserParams
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserParamsFilter, bool) (*entities.UserParams, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserParamsFilter, bool) *entities.UserParams); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserParams)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserParamsFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, userParams
func (_m *UserParamsRepository) Update(ctx context.Context, userParams *entities.UserParams) error {
	ret := _m.Called(ctx, userParams)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserParams) error); ok {
		r0 = rf(ctx, userParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserParamsRepository creates a new instance of UserParamsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserParamsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserParamsRepository {
	mock := &UserParamsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
