// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "backend/internal/dto"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserCaloriesRepository is an autogenerated mock type for the UserCaloriesRepository type
type UserCaloriesRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, uc
func (_m *UserCaloriesRepository) Create(ctx context.Context, uc *entities.UserCalories) error {
	ret := _m.Called(ctx, uc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserCalories) error); ok {
		r0 = rf(ctx, uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, f
func (_m *UserCaloriesRepository) Get(ctx context.Context, f dto.UserCaloriesFilter) (*entities.UserCalories, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.UserCalories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserCaloriesFilter) (*entities.UserCalories, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserCaloriesFilter) *entities.UserCalories); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserCalories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserCaloriesFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f
func (_m *UserCaloriesRepository) List(ctx context.Context, f dto.UserCaloriesFilter) ([]*entities.UserCalories, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.UserCalories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserCaloriesFilter) ([]*entities.UserCalories, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserCaloriesFilter) []*entities.UserCalories); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserCalories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserCaloriesFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, uc
func (_m *UserCaloriesRepository) Update(ctx context.Context, uc *entities.UserCalories) error {
	ret := _m.Called(ctx, uc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserCalories) error); ok {
		r0 = rf(ctx, uc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, f
func (_m *UserCaloriesRepository) Delete(ctx context.Context, f dto.UserCaloriesFilter) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserCaloriesFilter) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserCaloriesRepository creates a new instance of UserCaloriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCaloriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCaloriesRepository {
	mock := &UserCaloriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
