// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "backend/internal/dto"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserWeightRepository is an autogenerated mock type for the UserWeightRepository type
type UserWeightRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userWeight
func (_m *UserWeightRepository) Create(ctx context.Context, userWeight *entities.UserWeight) error {
	ret := _m.Called(ctx, userWeight)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserWeight) error); ok {
		r0 = rf(ctx, userWeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, f
func (_m *UserWeightRepository) Delete(ctx context.Context, f dto.UserWeightFilter) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserWeightFilter) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, f, withBlock
func (_m *UserWeightRepository) Get(ctx context.Context, f dto.UserWeightFilter, withBlock bool) (*entities.UserWeight, error) {
	ret := _m.Called(ctx, f, withBlock)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.UserWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserWeightFilter, bool) (*entities.UserWeight, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserWeightFilter, bool) *entities.UserWeight); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserWeight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserWeightFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f, withBlock
func (_m *UserWeightRepository) List(ctx context.Context, f dto.UserWeightFilter, withBlock bool) ([]*entities.UserWeight, error) {
	ret := _m.Called(ctx, f, withBlock)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.UserWeight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserWeightFilter, bool) ([]*entities.UserWeight, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserWeightFilter, bool) []*entities.UserWeight); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserWeight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserWeightFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, userWeight
func (_m *UserWeightRepository) Update(ctx context.Context, userWeight *entities.UserWeight) error {
	ret := _m.Called(ctx, userWeight)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserWeight) error); ok {
		r0 = rf(ctx, userWeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserWeightRepository creates a new instance of UserWeightRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserWeightRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserWeightRepository {
	mock := &UserWeightRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
