// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "backend/internal/dto"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// WorkoutsRepository is an autogenerated mock type for the WorkoutsRepository type
type WorkoutsRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, f, withBlock
func (_m *WorkoutsRepository) Get(ctx context.Context, f dto.WorkoutsFilter, withBlock bool) (*entities.Workout, error) {
	ret := _m.Called(ctx, f, withBlock)
	if len(ret) == 0 {
		panic("no return value specified for Get")
	}
	var r0 *entities.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.WorkoutsFilter, bool) (*entities.Workout, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.WorkoutsFilter, bool) *entities.Workout); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Workout)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, dto.WorkoutsFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Create provides a mock function with given fields: ctx, workout
func (_m *WorkoutsRepository) Create(ctx context.Context, workout *entities.Workout) error {
	ret := _m.Called(ctx, workout)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Workout) error); ok {
		r0 = rf(ctx, workout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Update provides a mock function with given fields: ctx, workout
func (_m *WorkoutsRepository) Update(ctx context.Context, workout *entities.Workout) error {
	ret := _m.Called(ctx, workout)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Workout) error); ok {
		r0 = rf(ctx, workout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Delete provides a mock function with given fields: ctx, f
func (_m *WorkoutsRepository) Delete(ctx context.Context, f dto.WorkoutsFilter) error {
	ret := _m.Called(ctx, f)
	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.WorkoutsFilter) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TopListWithLimit provides a mock function with given fields: ctx, f, limit, withBlock
func (_m *WorkoutsRepository) TopListWithLimit(ctx context.Context, f dto.WorkoutsFilter, limit int, withBlock bool) ([]*entities.Workout, error) {
	ret := _m.Called(ctx, f, limit, withBlock)
	if len(ret) == 0 {
		panic("no return value specified for TopListWithLimit")
	}
	var r0 []*entities.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.WorkoutsFilter, int, bool) ([]*entities.Workout, error)); ok {
		return rf(ctx, f, limit, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.WorkoutsFilter, int, bool) []*entities.Workout); ok {
		r0 = rf(ctx, f, limit, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Workout)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, dto.WorkoutsFilter, int, bool) error); ok {
		r1 = rf(ctx, f, limit, withBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NewWorkoutsRepository creates a new instance of WorkoutsRepository.
func NewWorkoutsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutsRepository {
	mock := &WorkoutsRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
