// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "backend/internal/dto"
	context "context"

	entities "backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserInfoRepository is an autogenerated mock type for the UserInfoRepository type
type UserInfoRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userInfo
func (_m *UserInfoRepository) Create(ctx context.Context, userInfo *entities.UserInfo) error {
	ret := _m.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.UserInfo) error); ok {
		r0 = rf(ctx, userInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, f, withBlock
func (_m *UserInfoRepository) Get(ctx context.Context, f dto.UserInfoFilter, withBlock bool) (*entities.UserInfo, error) {
	ret := _m.Called(ctx, f, withBlock)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserInfoFilter, bool) (*entities.UserInfo, error)); ok {
		return rf(ctx, f, withBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserInfoFilter, bool) *entities.UserInfo); ok {
		r0 = rf(ctx, f, withBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserInfoFilter, bool) error); ok {
		r1 = rf(ctx, f, withBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserInfoRepository creates a new instance of UserInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInfoRepository {
	mock := &UserInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
