// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Вход пользователя в систему и получение JWT токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная аутентификация",
                        "schema": {
                            "$ref": "#/definitions/models.JWTModel"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создание нового аккаунта пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequestModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь успешно зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/avatars": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Генерирует и скидывает ссылку для загрузки аватарки пользователя со стороны клиента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "Обработка аватарки",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PresignAvatarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная выдача публичной ссылки для загрузки",
                        "schema": {
                            "$ref": "#/definitions/models.PresignAvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exercises": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает список упражнений с возможностью фильтрации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Получение списка упражнений",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уровень подготовки (beginner, medium, sportsman)",
                        "name": "level_preparation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип упражнения (cardio, upper_body, lower_body, full_body, flexibility)",
                        "name": "type_exercise",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Место выполнения (home, gym, street)",
                        "name": "place_exercise",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список упражнений",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExerciseResponseModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID пользователя",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новое упражнение с указанными параметрами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Создание нового упражнения",
                "parameters": [
                    {
                        "description": "Данные для создания упражнения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciseRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Упражнение успешно создано",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат данных",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exercises/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает детальную информацию об упражнении по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Получение упражнения по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID упражнения",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Детальная информация об упражнении",
                        "schema": {
                            "$ref": "#/definitions/models.ExerciseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Упражнение не найдено",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет упражнение по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Удаление упражнения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID упражнения",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Упражнение успешно удалено",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Упражнение не найдено",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующее упражнение по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Обновление упражнения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID упражнения",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления упражнения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciseResponseModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Упражнение успешно обновлено",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Упражнение не найдено",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает основную информацию о пользователе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Info"
                ],
                "summary": "Получение информации пользователя",
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/models.UserInfoResponseModel"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет основную информацию о пользователе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Info"
                ],
                "summary": "Удаление информации пользователя",
                "responses": {
                    "200": {
                        "description": "Успешное удаление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет основную информацию о пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Info"
                ],
                "summary": "Обновление информации пользователя",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserInfoUpdateRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/params": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает дополнительные параметры пользователя (рост, возраст и т.д.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Params"
                ],
                "summary": "Получение параметров пользователя",
                "responses": {
                    "200": {
                        "description": "Параметры пользователя",
                        "schema": {
                            "$ref": "#/definitions/models.UserParamsResponseModel"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает дополнительные параметры пользователя (рост, возраст и т.д.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Params"
                ],
                "summary": "Создание параметров пользователя",
                "parameters": [
                    {
                        "description": "Данные параметров для создания",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserParamsCreateRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет дополнительные параметры пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Params"
                ],
                "summary": "Удаление параметров пользователя",
                "responses": {
                    "200": {
                        "description": "Успешное удаление",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет дополнительные параметры пользователя (рост, возраст и т.д.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Params"
                ],
                "summary": "Обновление параметров пользователя",
                "parameters": [
                    {
                        "description": "Данные параметров для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserParamsUpdateRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/weight": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает текущий вес пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Weight"
                ],
                "summary": "Получение текущего веса пользователя",
                "responses": {
                    "200": {
                        "description": "Актуальный (последний) вес пользователя",
                        "schema": {
                            "$ref": "#/definitions/models.UserWeightResponseModel"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новую запись о весе пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Weight"
                ],
                "summary": "Создание записи о весе пользователя",
                "parameters": [
                    {
                        "description": "Данные веса для создания",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserWeightCreateRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет текущий вес пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Weight"
                ],
                "summary": "Обновление веса пользователя (пока нет)",
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/weight/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает всю историю изменений веса пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Weight"
                ],
                "summary": "Получение истории веса пользователя",
                "responses": {
                    "200": {
                        "description": "История веса пользователя",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserWeightResponseModel"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/weight/{uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет запись о весе пользователя по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Weight"
                ],
                "summary": "Удаление записи о весе пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID записи о весе",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует авторизация",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.ExerciseType": {
            "type": "string",
            "enum": [
                "cardio",
                "upper_body",
                "lower_body",
                "full_body",
                "flexibility"
            ],
            "x-enum-varnames": [
                "Cardio",
                "UpperBody",
                "LowerBody",
                "FullBody",
                "Flexibility"
            ]
        },
        "entities.LevelPreparation": {
            "type": "string",
            "enum": [
                "beginner",
                "medium",
                "sportsman"
            ],
            "x-enum-varnames": [
                "Beginner",
                "Medium",
                "Sportsman"
            ]
        },
        "entities.Lifestyle": {
            "type": "string",
            "enum": [
                "not_active",
                "active",
                "sportive"
            ],
            "x-enum-varnames": [
                "NotActive",
                "Active",
                "Sportive"
            ]
        },
        "entities.PlaceExercise": {
            "type": "string",
            "enum": [
                "street",
                "gym",
                "home"
            ],
            "x-enum-varnames": [
                "Street",
                "Gym",
                "Home"
            ]
        },
        "entities.Want": {
            "type": "string",
            "enum": [
                "lose_weight",
                "build_muscle",
                "stay_fit"
            ],
            "x-enum-varnames": [
                "LoseWeight",
                "BuildMuscle",
                "StayFit"
            ]
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "{route} error": {
                    "type": "string",
                    "example": "{method}: {crud}: error message"
                }
            }
        },
        "models.ExerciseRequestModel": {
            "type": "object",
            "required": [
                "avg_calories_per",
                "base_count_reps",
                "base_relax_time",
                "level_preparation",
                "name",
                "place_exercise",
                "steps",
                "type_exercise"
            ],
            "properties": {
                "avg_calories_per": {
                    "type": "number",
                    "maximum": 1000,
                    "minimum": 0
                },
                "base_count_reps": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "base_relax_time": {
                    "type": "integer",
                    "maximum": 3600,
                    "minimum": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                },
                "level_preparation": {
                    "type": "string",
                    "enum": [
                        "beginner",
                        "medium",
                        "sportsman"
                    ]
                },
                "link_gif": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "place_exercise": {
                    "type": "string",
                    "enum": [
                        "home",
                        "gym",
                        "street"
                    ]
                },
                "steps": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "type_exercise": {
                    "type": "string",
                    "enum": [
                        "cardio",
                        "upper_body",
                        "lower_body",
                        "full_body",
                        "flexibility"
                    ]
                }
            }
        },
        "models.ExerciseResponseModel": {
            "type": "object",
            "properties": {
                "avg_calories_per": {
                    "type": "number"
                },
                "base_count_reps": {
                    "type": "integer"
                },
                "base_relax_time": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "level_preparation": {
                    "$ref": "#/definitions/entities.LevelPreparation"
                },
                "link_gif": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "place_exercise": {
                    "$ref": "#/definitions/entities.PlaceExercise"
                },
                "steps": {
                    "type": "integer"
                },
                "type_exercise": {
                    "$ref": "#/definitions/entities.ExerciseType"
                }
            }
        },
        "models.JWTModel": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequestModel": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.PresignAvatarRequest": {
            "type": "object",
            "required": [
                "content_type"
            ],
            "properties": {
                "content_type": {
                    "type": "string"
                }
            }
        },
        "models.PresignAvatarResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "object_key": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequestModel": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone",
                "surname",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Successfully {action}"
                }
            }
        },
        "models.UserInfoResponseModel": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserInfoUpdateRequestModel": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phone",
                "surname"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "phone": {
                    "type": "string"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                }
            }
        },
        "models.UserParamsCreateRequestModel": {
            "type": "object",
            "required": [
                "height",
                "lifestyle",
                "targetCaloriesDaily",
                "targetWeight",
                "targetWorkoutsWeeks",
                "wants"
            ],
            "properties": {
                "height": {
                    "type": "integer",
                    "maximum": 250,
                    "minimum": 100
                },
                "lifestyle": {
                    "type": "string",
                    "enum": [
                        "not_active",
                        "active",
                        "sportive"
                    ]
                },
                "photo": {
                    "type": "string"
                },
                "targetCaloriesDaily": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 0
                },
                "targetWeight": {
                    "type": "number",
                    "maximum": 300,
                    "minimum": 40
                },
                "targetWorkoutsWeeks": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 0
                },
                "wants": {
                    "type": "string",
                    "enum": [
                        "lose_weight",
                        "build_muscle",
                        "stay_fit"
                    ]
                }
            }
        },
        "models.UserParamsResponseModel": {
            "type": "object",
            "properties": {
                "currentWeight": {
                    "type": "number"
                },
                "height": {
                    "type": "integer"
                },
                "lifestyle": {
                    "$ref": "#/definitions/entities.Lifestyle"
                },
                "photo": {
                    "type": "string"
                },
                "targetCaloriesDaily": {
                    "type": "integer"
                },
                "targetWeight": {
                    "type": "number"
                },
                "targetWorkoutsWeeks": {
                    "type": "integer"
                },
                "wants": {
                    "$ref": "#/definitions/entities.Want"
                }
            }
        },
        "models.UserParamsUpdateRequestModel": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "maximum": 250,
                    "minimum": 100
                },
                "lifestyle": {
                    "type": "string",
                    "enum": [
                        "not_active",
                        "active",
                        "sportive"
                    ]
                },
                "photo": {
                    "type": "string"
                },
                "targetCaloriesDaily": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 0
                },
                "targetWeight": {
                    "type": "number",
                    "maximum": 300,
                    "minimum": 40
                },
                "targetWorkoutsWeeks": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 0
                },
                "wants": {
                    "type": "string",
                    "enum": [
                        "lose_weight",
                        "build_muscle",
                        "stay_fit"
                    ]
                }
            }
        },
        "models.UserWeightCreateRequestModel": {
            "type": "object",
            "required": [
                "weight"
            ],
            "properties": {
                "weight": {
                    "type": "number",
                    "maximum": 300,
                    "minimum": 10
                }
            }
        },
        "models.UserWeightResponseModel": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "Auth"
        },
        {
            "name": "User Weight"
        },
        {
            "name": "User Params"
        },
        {
            "name": "User Info"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
